version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - sliit-docker
    ports:
      - 21017:21017
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  
  backend:
    image: springboot-studentservice:1.0
    container_name: springboot-studentservice
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - sliit-docker
    links:
      - mongodb
    
  frontend:
    image: sliit-docker-client-app:v1.0
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - sliit-docker
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  sliit-docker:
    driver: bridge

volumes:
  mongodb:
  mongodb_config:
